# Generated by Django 4.1.1 on 2022-10-10 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_is_open_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_open',
        ),
    ]
